### ISSUE TITLE
NPE in CRLRule

### ISSUE THREAD

**Issue by thxmasj** [difi/certvalidator#2]
A NullPointerException might occur in CRLRule, as the stacktrace below shows. As far as I can see this happens when the rule encounters an X.509 CRL which does not have the [Next update](https://tools.ietf.org/html/rfc5280#section-5.1.2.5) field. I'm unfortunately not able to provide information about which issuer that returned this CRL. However, I think the rule could handle this scenario better, either by issuing a new fetch, use the current CRL for validation, or fail the validation.

```java
java.lang.NullPointerException: null
        at no.difi.certvalidator.rule.CRLRule.validate(CRLRule.java:50) ~[commons-certvalidator-2.0.1.jar:na]
        at no.difi.certvalidator.structure.AndJunction.validate(AndJunction.java:23) ~[commons-certvalidator-2.0.1.jar:na]
        at no.difi.certvalidator.Validator.validate(Validator.java:49) ~[commons-certvalidator-2.0.1.jar:na]
        at no.difi.common.support.CertificateValidatorInterceptor.validateMessage(CertificateValidatorInterceptor.java:47) ~[CertificateValidatorInterceptor.class:na]
```

**Comment by klakegg** [comment]
Could you please try the updated version?

**Comment by thxmasj** [comment]
Fix OK.
